### ISSUE TITLE
Answers returned from progress/{username} must contain the question and the competence to be unique.

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#100]
Currently answers only contain:
{
datecreated:1477511319812
questionId:"SchönuserWie möchtest du das Lernziel erreichen?1477511319812"
text:"Schön"
userId:"user"
}
But it is not possible to tell for which competence the question was answered.

**Comment by juliandehne** [comment]
/api1/progress/{userId} liefert die Antworten geordnet nach den Kompetenzen zurück z.B.

{
  "userCompetenceProgressList": [
    {
      **"competence": "Die Studierenden vergleichen drei Sätze anhand ihrer Bausteine",**
      "competenceLinksView": null,
      "abstractAssessment": [
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen drei Sätze anhand ihrer BausteineASSESSMENT",
          "learningGoal": null,
          "typeOfSelfAssessment": "ASSESSMENT"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen drei Sätze anhand ihrer BausteineMOTIVATION",
          "learningGoal": null,
          "typeOfSelfAssessment": "MOTIVATION"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen drei Sätze anhand ihrer BausteinePROGRESS",
          "learningGoal": null,
          "typeOfSelfAssessment": "PROGRESS"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen drei Sätze anhand ihrer BausteineEPOSTYPE",
          "learningGoal": null,
          "typeOfSelfAssessment": "EPOSTYPE"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen drei Sätze anhand ihrer BausteineTIME",
          "learningGoal": null,
          "typeOfSelfAssessment": "TIME"
        }
      ],
      "reflectiveQuestionAnswerHolder": {
        "data": [
          {
            "text": "gute Antwort2",
            "userId": "Mephisto",
            "questionId": "gute Antwort2Mephistoeine wichtige Frage?21478009308618",
            "datecreated": 1478009308618
          },
          {
            "text": "gute Antwort1",
            "userId": "Mephisto",
            "questionId": "gute Antwort1Mephistoeine wichtige Frage?21478009308403",
            "datecreated": 1478009308403
          },
          {
            "text": "gute Antwort2",
            "userId": "Mephisto",
            "questionId": "gute Antwort2Mephistoeine wichtige Frage?1478009308230",
            "datecreated": 1478009308230
          },
          {
            "text": "gute Antwort1",
            "userId": "Mephisto",
            "questionId": "gute Antwort1Mephistoeine wichtige Frage?1478009308010",
            "datecreated": 1478009308010
          }
        ]
      }
    },
    {
      **"competence": "Die Studierenden vergleichen zwei Sätze anhand ihrer Bausteine",**
      "competenceLinksView": null,
      "abstractAssessment": [
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen zwei Sätze anhand ihrer BausteineASSESSMENT",
          "learningGoal": null,
          "typeOfSelfAssessment": "ASSESSMENT"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen zwei Sätze anhand ihrer BausteineMOTIVATION",
          "learningGoal": null,
          "typeOfSelfAssessment": "MOTIVATION"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen zwei Sätze anhand ihrer BausteinePROGRESS",
          "learningGoal": null,
          "typeOfSelfAssessment": "PROGRESS"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen zwei Sätze anhand ihrer BausteineEPOSTYPE",
          "learningGoal": null,
          "typeOfSelfAssessment": "EPOSTYPE"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoDie Studierenden vergleichen zwei Sätze anhand ihrer BausteineTIME",
          "learningGoal": null,
          "typeOfSelfAssessment": "TIME"
        }
      ],
      "reflectiveQuestionAnswerHolder": {
        "data": [
          {
            "text": "gute Antwort2",
            "userId": "Mephisto",
            "questionId": "gute Antwort2Mephistoeine wichtige Frage?21478009308618",
            "datecreated": 1478009308618
          },
          {
            "text": "gute Antwort1",
            "userId": "Mephisto",
            "questionId": "gute Antwort1Mephistoeine wichtige Frage?21478009308403",
            "datecreated": 1478009308403
          },
          {
            "text": "gute Antwort2",
            "userId": "Mephisto",
            "questionId": "gute Antwort2Mephistoeine wichtige Frage?1478009308230",
            "datecreated": 1478009308230
          },
          {
            "text": "gute Antwort1",
            "userId": "Mephisto",
            "questionId": "gute Antwort1Mephistoeine wichtige Frage?1478009308010",
            "datecreated": 1478009308010
          }
        ]
      }
    },
    {
      "competence": "Ich bin in der Lage eine Masterarbeit zu konzipieren",
      "competenceLinksView": [
        {
          "abstractLinkId": "Ich bin in der Lage eine Masterarbeit zu konzipierenHttp://meinefressewoistdasdenn",
          "evidenceTitel": null,
          "evidenceUrl": "Http://meinefressewoistdasdenn",
          "comments": [
            {
              "created": 1478009309798,
              "commentId": "1478009309798läuft gut2",
              "commentedCommentId": null,
              "linkId": null,
              "user": "Mephisto",
              "text": "läuft gut2",
              "courseContext": null
            },
            {
              "created": 1478009309583,
              "commentId": "1478009309583läuft gut",
              "commentedCommentId": null,
              "linkId": null,
              "user": "Mephisto",
              "text": "läuft gut",
              "courseContext": null
            },
            {
              "created": 1478001355658,
              "commentId": "1478001355658läuft gut2",
              "commentedCommentId": null,
              "linkId": null,
              "user": "Mephisto",
              "text": "läuft gut2",
              "courseContext": null
            },
            {
              "created": 1478001355447,
              "commentId": "1478001355447läuft gut",
              "commentedCommentId": null,
              "linkId": null,
              "user": "Mephisto",
              "text": "läuft gut",
              "courseContext": null
            },
            {
              "created": 1478001342756,
              "commentId": "1478001342756läuft gut2",
              "commentedCommentId": null,
              "linkId": null,
              "user": "Mephisto",
              "text": "läuft gut2",
              "courseContext": null
            },
            {
              "created": 1478001342550,
              "commentId": "1478001342550läuft gut",
              "commentedCommentId": null,
              "linkId": null,
              "user": "Mephisto",
              "text": "läuft gut",
              "courseContext": null
            }
          ],
          "validated": null
        }
      ],
      "abstractAssessment": [
        {
          "assessmentIndex": 3,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoIch bin in der Lage eine Masterarbeit zu konzipierenASSESSMENT",
          "learningGoal": null,
          "typeOfSelfAssessment": "ASSESSMENT"
        },
        {
          "assessmentIndex": 2,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoIch bin in der Lage eine Masterarbeit zu konzipierenMOTIVATION",
          "learningGoal": null,
          "typeOfSelfAssessment": "MOTIVATION"
        },
        {
          "assessmentIndex": 2,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoIch bin in der Lage eine Masterarbeit zu konzipierenPROGRESS",
          "learningGoal": null,
          "typeOfSelfAssessment": "PROGRESS"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoIch bin in der Lage eine Masterarbeit zu konzipierenEPOSTYPE",
          "learningGoal": null,
          "typeOfSelfAssessment": "EPOSTYPE"
        },
        {
          "assessmentIndex": 0,
          "minValue": 0,
          "maxValue": 0,
          "assessmentId": "MephistoIch bin in der Lage eine Masterarbeit zu konzipierenTIME",
          "learningGoal": null,
          "typeOfSelfAssessment": "TIME"
        }
      ],
      "reflectiveQuestionAnswerHolder": {
        "data": []
      }
    }
  ]
}

**Comment by juliandehne** [comment]
Added JUNIT Test for the example above:
uzuzjmd.competence.tests.ProgressApiTests

**Comment by juliandehne** [comment]
Eine Alternative könnte auch die Schnittstelle:
/api1/progress/{userId}/competences/{competenceId}
sein. Liefert nur das Progress-Modell für eine einzelne Kompetenz
