### ISSUE TITLE
competences/{competenceId}/questions should return a list of questions, not question-IDs.

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#101]
competences/{competenceId}/questions returns only the question-IDs not the Question. My hack is splitting the ID by ? and take the first part.

**Comment by uzuzjmd** [comment]
fixed in latest commit; 
competences/{competenceId}/questions now returns:

[
  {
    "question": "string",
    "competenceId": "string",
    "questionId": "string"
  }
]
