### ISSUE TITLE
Standalone Installer for Linux Systems

### ISSUE THREAD

**Issue by uzuzjmd** [uzuzjmd/COMPBASE#11]

**Comment by B3J4y** [comment]
Integrated and tested with Ubuntu 15.04. https://github.com/uzuzjmd/Wissensmodellierung/commit/269a6473713ee19e33a5ae49705f899f0025c903

**Comment by uzuzjmd** [comment]
Can be closed if no further questions remain.

**Comment by uzuzjmd** [comment]
Should be adapted to neo4j backend
