### ISSUE TITLE
automatic generated cycle graph

### ISSUE THREAD

**Issue by xuananh** [uzuzjmd/COMPBASE#32]
When i send Graph with:
fromNode: a2, toNode: a3,
fromNode: a1, toNode: a2,
fromNode: a1, toNode: a7
fromNode: a2, toNode: a5
fromNode: a3, toNode: a4,
fromNode: a5, toNode: a6

then get from Server Graph with more edge:
fromNode: a2, toNode: a3
fromNode: a1, toNode: a2
fromNode: a1, toNode: a7
fromNode: a6, toNode: a1 -> that ist more
fromNode: a3, toNode: a4
fromNode: a2, toNode: a5 -> that ist more
fromNode: a5, toNode: a7 -> that ist more
fromNode: a5, toNode: a6

**Comment by uzuzjmd** [comment]
fixed this in backend

**Comment by uzuzjmd** [comment]
if there is a testcase could be reopened
