### ISSUE TITLE
Crawler: Search PLE

### ISSUE THREAD

**Issue by uzuzjmd** [uzuzjmd/COMPBASE#50]
Bei der Suche nach Personal Learning Environment wird nichts gefunden

![results_ple](https://cloud.githubusercontent.com/assets/1481930/14819333/e39547c6-0bc1-11e6-807b-4ff3f4ab7c29.png)

**Comment by B3J4y** [comment]
One of the problems was that the desired website wasn't in the pool of crawled websites. So, maybe a deeper crawl would solve this issue.
