### ISSUE TITLE
Implement endpoint to get all users in a course

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#61]
Data should contain if a user is teacher or learner.
Only users who use the system actively should be returned.

**Comment by uzuzjmd** [comment]
implemented. Cannot be automatically testest without committing username and password. Thus manual testing is required. Will return a List of UserData objects with a field lmsSystem that shows if the the data is from moodle or the db. If the user has used the app the field should be set to "mobile"
