### ISSUE TITLE
Allow access to RestServer via local area network (192.168.x.x)

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#69]
To test the app on an android emulator or on devices, the local rest server can't be accessed via their LAN-address, what should be possible.

**Comment by uzuzjmd** [comment]
http://stackoverflow.com/questions/6760585/accessing-localhostport-from-android-emulator
schon probiert?

**Comment by uzuzjmd** [comment]
look at mobile setup here: https://github.com/uzuzjmd/COMPBASE/wiki/Development-Setup
