### ISSUE TITLE
java: package uzuzjmd.competence.reflexion.dao does not exist

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#72]
Can't run the tests in LearningTemplateApi1Test because **uzuzjmd.competence.reflexion.dao** does not exist.
I found LearningTemplateDao in package **de.unipotsdam.anh.dao** not in **uzuzjmd.competence.reflexion.dao**

Do I have to change the package name in LearningTemplateDaoTest or what can be the problem?

**Comment by uzuzjmd** [comment]
most likely you did not update the submodules. If that is not the problem try reinstallen the competence-learner and competence-teacher submodules

**Comment by uzuzjmd** [comment]
https://github.com/uzuzjmd/COMPBASE/wiki/Submodules

**Comment by mantir** [comment]
**git submodule update --recursive** needed to be executed with sudo because of some permission denied errors.
