### ISSUE TITLE
In api1 the courseId should be settable while adding a competence.

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#75]
I can't store competences connected to the course context "randomString". All competences are connected to "university" and therefore can't be fetched as the users competences if the user is not connected to "university".

**Comment by uzuzjmd** [comment]
solution 1) Add competence to learning template. Add user to learning template.
solution 2) User API to connect course and competence (if user is part of course)
see https://github.com/uzuzjmd/COMPBASE/issues/77 for temporary solution
