### ISSUE TITLE
Get the real names of users from Moodle or other LMS if given

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#79]
To be more transparent it would be nice to show the real names of the people.

**Comment by uzuzjmd** [comment]
Problem: LMS is holding the information about the user (cannot be retrieved without problems in privacy for a general user (without course membership etc.))

Solution:
1) Use /api1/users/{userId}/exists to verify its existence first. 
2) Use /api1/users/{userId} to persist full name of users after first login. 
3) Store locally that user is not using the app for the first time.
4) Use /api1/users/{userId} to get full user details
