### ISSUE TITLE
Create activities just in compbase

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#80]
It would be nice to be able to create activities that are not coming from a LMS.

**Comment by uzuzjmd** [comment]
Das ging schon (früheres issue)

 @Test
    public void createUserProgress() throws Exception {

        User userDao = new User(user);
        userDao.printableName = user;
        userDao.persist();


Siehe ProgressApiTests:

 

>        // create evidence Link
>         CompetenceLinksView competenceLinksView1 = new CompetenceLinksView();
>         competenceLinksView1.setEvidenceTitel("Ich habe einen UI-Protoyp erstellt");
>         competenceLinksView1.setEvidenceUrl("Http://meinefressewoistdasdenn");
>         competenceLinksView1.setValidated(false);
>         CommentEntry commentEntry = new CommentEntry("julian", "läuft gut", System.currentTimeMillis());
>         competenceLinksView1.setComments(Arrays.asList(commentEntry));
>         SelfAssessment assessment = new SelfAssessment(new Competence(competenceString), new User(user), 3, true);
>         AbstractAssessment abstractAssessments1 = assessment.toAbstractAssessment();
>         UserCompetenceProgress userCompetenceProgress = new UserCompetenceProgress(competenceString, new CompetenceLinksView[] {competenceLinksView1}, abstractAssessments1);
>         Response response = target("/api1/progress/"+user+"/competences/"+competenceString).request().put(Entity.entity(userCompetenceProgress, MediaType.APPLICATION_JSON));
>         assertTrue(response.getStatus() == 200);
> 
>     }

**Comment by uzuzjmd** [comment]
created activityImpl (not tested) that allows to 
- add new activity (regardless of link to user)
- connect them to competences
- query that connection
- link to user should still be done over evidenceApi (informell activity and formal activity distinguised by type of link-url given)

**Comment by uzuzjmd** [comment]
needs tests

**Comment by uzuzjmd** [comment]
the link to the user could be implemented with a new edge "interestedIn" - going to investigate.

**Comment by uzuzjmd** [comment]
started implementing tests, there are bugs....

**Comment by uzuzjmd** [comment]
TODO implement other tests if needed.
