### ISSUE TITLE
Feature to let users answer reflective questions to a competence.

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#88]
It would be possible to add a free text field to a Progress.
The questions are coming from outside.
Wie motiviert bist du das Lernziel zu erreichen?
1 - 5
Was wird ein Ergebnis deines Lernens sein? (Textdokument, Computerprogramm)
Freitext

**Comment by uzuzjmd** [comment]
This are are 3 different features. 1.) add a reflective question to a competence 2.) add a motivation score to a competence 3.) add a product

1.) will be implemented as a new interface
2.) will be added to the self assessment object
3.) will also be added to the self assessment object

**Comment by uzuzjmd** [comment]
Pushed changed api to server:

**For the self assessments try:**

Try: 
http://fleckenroller.cs.uni-potsdam.de/doku/api/#!/default/getUserProgress
with julian@stuff.com

For the reflective questions try: 
http://fleckenroller.cs.uni-potsdam.de/doku/api/#!/default/getReflectiveQuestionsForCompetence
and
http://fleckenroller.cs.uni-potsdam.de/doku/api/#!/default/addReflectiveQuestionToCompetence

**Comment by uzuzjmd** [comment]
Note: If you are using PUT  you normally do not need to provide IDs (they are part of the exchange object but are created on the server side.

**Comment by uzuzjmd** [comment]
Still needs interface to add answers in the database.

**Comment by uzuzjmd** [comment]
http://localhost/moodle/swagger/#!/default/addReflectiveQuestionsAnswersForCompetence 
http://localhost/moodle/swagger/#!/default/addReflectiveQuestionToCompetence
http://fleckenroller.cs.uni-potsdam.de/doku/api/#!/default/updateOrCreateUserProgress 
all allow the reflective questions which are also included in the progress

**Comment by uzuzjmd** [comment]
Update of progress does not update reflective questions
