### ISSUE TITLE
How is it possible to know which username from the DB belongs to which username in Moodle?

### ISSUE THREAD

**Issue by mantir** [uzuzjmd/COMPBASE#90]
Login data:  {username: "name", password: "*****"} 
Data from Users returned from the api:  {username: "3134", name: "Forename Surname", role: "student", courseContext: "22", fromSystem: "moodle"}

From the login data it is not possible to know which user one self is, when retrieving the user list of a course because the **username** in Moodle is returned as some numeric representation and the **name** is the full, fore- and surname, but I need the login name of the user to know who I am.

**Comment by uzuzjmd** [comment]
Instead of producing the forename and surname, the api now produces the moodle name.  If that is sufficient, please close the issue.
